name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Maven and Install Core
        run: mvn install -pl asyncapi-generator-core,asyncapi-generator-cli,asyncapi-generator-maven-plugin -am --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Run Gradle Plugin Tests
        working-directory: asyncapi-generator-gradle-plugin
        run: ./gradlew test -PasyncApiGeneratorVersion=1.0-SNAPSHOT
